skeleton:
  year:
    min: 2015
    max: 2020
  age:
    min: 0
    max: 100
  sex: {Male: 'Male', Female: 'Female'}
  region: [
    'AT',
    'AU',
    'BE',
    'BG',
    'CA',
    'CH',
    'CL',
    'CZ',
    'DE',
    'DK',
    'EE',
    'ES',
    'FI',
    'FR',
    'GB-EAW',
    'GB-NIR',
    'GB-SCT',
    'GR',
    'HR',
    'HU',
    'IL',
    'IS',
    'IT',
    'KR',
    'LT',
    'LU',
    'LV',
    'NL',
    'NO',
    'NZ',
    'PL',
    'PT',
    'RU',
    'SE',
    'SI',
    'SK',
    'TW',
    'US'
]
regions_for_all_cause_analysis: [
    'AT',
    #'AU', coarse age groups, missing weeks
    'BE',
    'BG',
    #'CA', coarse age groups, missing weeks
    'CH',
    'CL',
    'CZ',
    'DE',
    'DK',
    'EE',
    'ES',
    'FI',
    'FR',
    'GB-EAW',
    'GB-NIR',
    'GB-SCT',
    'GR',
    'HR',
    'HU',
    #'IL', # coarse age groups
    'IS',
    'IT',
    #'KR', # coarse age group
    'LT',
    #'LU', # adolescent hazard profiles in 2019 very different from 2020
    #'LV', # adolescent hazard profiles in 2019 very different from 2020
    'NL',
    'NO',
    #'NZ', # coarse age groups
    'PL',
    'PT',
    'RU', # new!
    'SE',
    'SI',
    'SK',
    #'TW', # signs for under-registration of deaths in 2020
    'US'
]
regions_for_covid_cause_analysis: [
    'BE',
    'CH',
    'CL',
    'CZ',
    'DE',
    'DK',
    'ES',
    'FR',
    'GB-EAW',
    'GB-SCT',
    'GR',
    'IT',
    'NL',
    'PT',
    'SI',
    # added new 2021-05-26
    'US',
    'NO',
    'HU',
    # 'AT' temporarily discarded, appear NAs in lt_input
]
